### PR TITLE
Use ToolforgeBundle's session storage class

### PR DESCRIPTION
**Pull request by samwilson**
This adds the correct URL path to the session cookie.

Bug: T219946

### CODE REVIEW

**Comment by samwilson** [comment]
I suspect there's a better way of doing this, but because Symfony switches between native session storage and mock file session storage (for web and CLI access respectively) it's not obvious to me how we're meant to override the session storage class. Anyway, the base URL is something that's usually in a config file anyway because it can be useful for making links to the site when there's no request context.

**Comment by MaxSem** [comment]
Looks like you can do this in runtime: https://stackoverflow.com/q/24766260/1033612

**Comment by samwilson** [comment]
That's odd... it's what I tried earlier. I'll have another look. Thanks :)

**Comment by samwilson** [comment]
I've add it to the bundle instead: https://github.com/wikimedia/ToolforgeBundle/pull/17

And will update this PR to use it after that is merged and tagged.

**Comment by samwilson** [comment]
Okay this is ready now.

Ignore the CircleCI failure, I'm just trialing that for another branch.

**Pull request merged**
