### PR TITLE
Render PNGs more efficiently

### PR DESCRIPTION
**Pull request by samwilson**
Use file redirection in the OS shell to render PNG file rather
than reading them into memory. This also makes the rendering
an atomic operation from the application's point of view, so
perhaps will fix the issue with returning incomplete PNGs to the
client.

Bug: T219335

### CODE REVIEW

**Comment by MusikAnimal** [comment]
I'll admit I don't understand the concepts here, but at any rate I'm getting a JS error when I try to add translations:
```
TypeError: Cannot read property 'text' of undefined
```
this is from https://github.com/wikimedia/svgtranslate/blob/858f67bbb6c92b1d44b2765fc44f64d7f7e6d2da/assets/translate.js#L138

**Comment by samwilson** [comment]
I don't think that JS error is being caused by this patch.

Basically, what is changing here is that instead of running the `rsvg-convert` command and reading the output into memory and later writing it to a file, we're running a `rsvg-convert > out-file.png` command, to create the same file.

However, this was an experiment trying to figure out where the half-loading images were coming from, and doesn't solve that issue so we don't really need to merge this now. I do think changing to this is a tiny bit more efficient though. It also uses `Process::mustRun()` instead of `run()` followed by error-checking (which is what mustRun does for us). Pretty minor, all up.

**Comment by MusikAnimal** [comment]
Do we still want to get this merged? It's labeled ready for review, but it's been so long I wanted to double-check.

**Comment by samwilson** [comment]
Yep, this is still good to go.

**Comment by MusikAnimal** [comment]
Alright, well the TypeError was my only concern, and you say it's unrelated. Merging!

**Pull request merged**
