### PR TITLE
Update pt-br.json

### PR DESCRIPTION
**Pull request by eduaddad**
complete translation into Brazilian Portuguese

### CODE REVIEW

**Comment by samwilson** [comment]
Thanks for this @eduaddad! This looks fine, but normally translations are managed via https://translatewiki.net — would you mind submitting these there? That way, they get proofread by a second Portuguese-speaking user before being merged here.

**Comment by eduaddad** [comment]
At the https://translatewiki.net There is no translation for this file.

**Comment by samwilson** [comment]
I do apologize! I totally forgot that we've got yet got it set up there. :-)

**Comment by eduaddad** [comment]
Thank you

If you want to translate to Portuguese (pt), just change the idioma to língua.

Language to Portuguese = Língua
Configuration = Definições

**Pull request merged**
