### PR TITLE
Upgrade to PHP 8.2 and update i18n files

### PR DESCRIPTION
**Pull request by samwilson**

### CODE REVIEW

**Comment by MusikAnimal** [comment]
I can't repro the failure on my local (PHP 8.1) either. Should we ignore the 8.1 failure for now so that this and #723 can be moved along?

**Comment by samwilson** [comment]
Yeah, probably!

I just don't know if it's hiding some sort of obvious error somewhere (in PHP 7.4 as well, maybe). We've had enough issues with the namespace stuff, it wouldn't surprise me if it's doing something wrong somewhere.

**Comment by samwilson** [comment]
Now failing with:

> PHP Fatal error:  Declaration of PhpParser\ParserAbstract::parse(string $code, ?PhpParser\ErrorHandler $errorHandler = null) must be compatible with PhpParser\Parser::parse(string $code, ?PhpParser\ErrorHandler $errorHandler = null): ?array in /home/runner/work/svgtranslate/svgtranslate/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php on line 158

This seems to be because `nikic/php-parser` is being held back to v4 by `symfony/maker-bundle`, and we can't update that because newer versions require Symfony 6.3. It might be easier to remove the maker bundle for now (it's not like we're using it any more really).

**Comment by samwilson** [comment]
I'm making a mess here aren't I?! :-) Sorry.

Ignore this one; I've put the essential bits into #725, and after that's done will think about the PHP 8.2 upgrade.

**Pull request closed without merging**
