### PR TITLE
Add the language settings dialog

### PR DESCRIPTION
**Pull request by samwilson**
Bug: https://phabricator.wikimedia.org/T204849

### CODE REVIEW

**Comment by aezell** [comment]
Two things I see initially:
1) Inconsistent capitalization for the language names in the dropdown. I assume this is controlled by ULS so I don't know how/if we can change it.
2) If I click or tab into the the "Preferred languages" text box and start typing before the search modal pops up, I can type anything and there's no search that will happen. I can tab away and the text box will be highlighted red to show me that there's an invalid item. I can click back in and add valid items. I think we need to activate the search modal faster, if possible.

**Comment by samwilson** [comment]
Language names are in their native languages, so follow those langauges' rules for capitalization; lots don't capitalize much. And yep, it's all handled by ULS so we can leave it to upstream to get it right (or wrong).

And it's a good point about the 'preferred languages' widget... it's got weirdnesses! At the moment it's doing the simplest possible, and not overriding any specific behaviour. I'll extend ULS and make it work as we want (I think I was being lazy and was planning on doing this in a future patch, but it might as well all happen here).

**Comment by samwilson** [comment]
I think there's going to be some more complexity to this, but could you have a look at the latest and see how it works for you?

ULS is not designed to be attached to a text input, but rather to a clickable element, and so there's some strange interactions between focussing the text input, clicking it, and opening the ULS dialog. I've fixed some of this by doing away with the input, but I'm not quite sure it's catching everything we want. It's hard to extend the ULS class without doing ugly things, so I've avoided doing that; we can go down that route if we need to (or perhaps add functionality to ULS to make all this easier).

Anyway, see what you think.

**Comment by mooeypoo** [comment]
> Two things I see initially:
> 
> 1. Inconsistent capitalization for the language names in the dropdown. I assume this is controlled by ULS so I don't know how/if we can change it.

Yeah, as @samwilson pointed out, this is a feature, not a bug :) There are quite a number of languages that don't capitalize as a rule.

> Are we concerned about accessibility here? Tabbing into that field doesn't open the ULS modal at all.

We should be aware of accessibility; I'm going to delve into this a bit deeper to offer help, but since this is a button, it probably will only work when clicked (so tab into it + space/enter should work) but in that case, we should probably make sure it's clear that this element should be pressed to work.

**Comment by mooeypoo** [comment]
So, I think I have a solution to both making sure that the events of the widget don't interfere with ULS and the accessibility; OOUI has an "ActionFieldLayout" that accepts a widget, a button, and then a config (label, positioning, etc, similar to the straight forward FieldLayout)

We could, then, transform the OO.ui.FieldLayout. Something like this, in `LanguadDialog.js`:

```
	this.preferredLangsWidget = new App.UlsTagMultiselectWidget();
	this.ulsButton = new OO.ui.ButtonWidget( { label: 'Add language' } );
	// Set up ULS on the widget.
	this.ulsButton.$element.uls( {
		ulsPurpose: 'preferredLangs',
		onSelect: this.preferredLangsWidget.onUlsSelect.bind( this.preferredLangsWidget )
	} );
	preferredLangsField = new OO.ui.ActionFieldLayout(
		this.preferredLangsWidget,
		this.ulsButton,
		{
			align: 'top',
			label: $.i18n( 'preferred-langs-field-label' ),
			help: $.i18n( 'preferred-langs-field-help' ),
			helpInline: true
		}
	);
```
(This was an experiment, so I didn't bother bringing the onUlsSelect method over to the dialog, but if we go that way we should probably do that)

This would mean that we have an extra button in there, true, BUT it would also mean this is accessible and we don't risk event collision with clicking inside the widget and having ULS "hijack" the events (or clash with internal events of the widget)

Do we need to get approval from @prtksxna ? This would mean the widget would look something like this: 

[ (TagMultiselectWidget) ][ (button) Add Language ]

**Comment by mooeypoo** [comment]
Okay, I am going to take this whole thing a step further. @samwilson @aezell check this out. This absolutely CAN (probably should) be done as a followup commit but it will also probably fix 90% of the problems, and make our lives easier. I didn't know where else to post the results of my investigation, so here it is. We can move it to, perhaps, a task, later, if needed.

I have an almost-done code on my laptop, but since Github doesn't really work really well with stacked commits, I didn't want to push a change here. We can peer on this if you want, @samwilson 

I wanted to look into not using the ULS dialog itself and instead use MenuTagMultiselectWidget with the language list filled in as menu items. I initially thought this would be a bit of a nightmare, but after examining VisualEditor's code, this is actually fairly straight forward.

Here's what I tried -- 

1. ULS has a method called $.uls.data.getAutonyms(); that method returns an object with the keys as language codes and the values as the language name in its own language. We can map this into items for MenuTagMultiselectWidget:

In UlsTagMultiselectWidget.js constructor:
```
App.UlsTagMultiselectWidget = function AppUlsTagMultiselectWidget( config ) {
	// in the initial var statement
	ulsAutonyms = $.uls.data.getAutonyms(),
	langItems = [];

	// ...
	// (Before the TagMultiselect constructor:
	// Build language items
	$.each( ulsAutonyms, function ( code, lang ) {
		langItems.push( {
			data: code,
			label: lang
		} );
	} );

	// Call the parent constructor.
	config = $.extend( {
		// All ULS languages are allowed.
		allowedValues: Object.keys( $.uls.data.languages ),
		// The stored languages are selected.
		selected: preferredLangsData,
		options: langItems,
		inputPosition: 'outline'
	}, config );
	App.UlsTagMultiselectWidget.parent.call( this, config );
```
And get rid of the this.$element.uls(...) thing entirely.

2. Out of the box, the above works to show a list of languages in their own language. The filtering half-works, because MenuSelectWidget (which the MenuTagMultiselectWidget uses as default) has a filtering method that looks at the labels (yeah, we need to change that, but whatever). So the next step, is to change the way filtering works. We can do that by extending MenuSelectWidget's `getItemMatcher`.

Create a menu, like App.UlsMenuSelectWidget that extends OO.ui.MenuSelectWidget and override getItemMatcher to return a matching function that takes into account the language code (so, item.getData() rather than item.getLabel())

3. Extend the method for `createMenuWidget` in App.UlsTagMultiselectWidget to return our extended menu, something like -
```	
return new App.UlsMenuSelectWidget( menuConfig );
```

4. Add a second overlay to the <body> and pass it through the config to the menu of the MenuTagMultiselectWidget.

This will make it possible to not bother with the connection between the TagMultiselectWidget and the ULS dialog.

**Comment by samwilson** [comment]
> Why are all the language files updated in this PR?

Sorry, yeah these aren't really necessary, but without them the tool-language selector is empty; I added them in to demonstrate that it works, and that it contains a different list of languages to the ULS for the preferred languages. They were generated with the import script from Grantmetrics.

So the things remaining to fix in this patch are:
* close all ULSes when the dialog closes;
* add button to open ULS for the preferred-langs widget.

I'm not really sure about the idea of having a different language-selection list for the preferred-languages list. If we were going to do that there, why not also just have an autocomplete list for the tool-language? But I'm happy with whatever yall decide. :)

**Comment by samwilson** [comment]
The two above changes are done now. See also my comments on the phab ticket though. There's more to be done here I think.

**Comment by samwilson** [comment]
The ULS menus were not calculating their heights correctly (as Niharika pointed out); that should now be fine. It feels a bit hacky, because we're just doing the same calculation that ULS is already doing, but we're doing it later than it does it so the final position of the button is known.

Ready for review again.

**Pull request merged**
