### PR TITLE
Update OOUI to 0.49

### PR DESCRIPTION
**Pull request by samwilson**
Change to a hacky but functional way of loading jQuery, to get around the changes with jQuery 3.4.1.

Bug: T233182

### CODE REVIEW

**Comment by MusikAnimal** [comment]
I was not able to get this to work on my local. Using Node 16.20.0 (as per the `.nvmrc` file), `npm run build` gives me:

```
Error: Cannot find module '/home/musikanimal/dev/svgtranslate/node_modules/object-visit/index.js'. Please verify that the package.json has a valid "main" entry
```

I know it's outside the scope of this PR, but I think we should start using the same Node/NPM as we do for MediaWiki. Or put more simply, just use https://www.mediawiki.org/wiki/Fresh/ (currently Node 18.17.0, NPM 9). This way everyone gets a consistent environment.

The Docker container doesn't appear to work anymore, either :(

**Comment by samwilson** [comment]
Docker fixed in #755 (thanks for review!).

I'm not able to replicate your error.

As for using the same version as MediaWiki, I agree, but in this case we'd be deploying with the `node18` image on toolforge, which is on Node 18.19.0 so that makes most sense. That said, we should be using 16.17.1 which is what the `node16` image has!

I'll update to 18 in this patch. Maybe that'll magically avoid the issue you're seeing. :-P

**Comment by samwilson** [comment]
Okay, see what you think now.

**Review by MusikAnimal — APPROVED** [review]
works great, tested using Docker

**Pull request merged**
