### PR TITLE
Add rest of Bootstrap, and enable tutorial box

### PR DESCRIPTION
**Pull request by samwilson**

### CODE REVIEW

**Comment by mooeypoo** [comment]
Wait, why are we adding bootstrap? Aren't we using ooui?

**Comment by samwilson** [comment]
I was basing it on the prototype.

@prtksxna is Bootstrap a hard requirement? Or was that just for convenience in prototyping?

**Comment by prtksxna** [comment]
Yep, it was just for my convenience while prototyping.

**Comment by samwilson** [comment]
Ah no worries. I'll remove it in the ooui branch.

**Pull request merged**
