### PR TITLE
Add zoom and pan to image (with Leaflet)

### PR DESCRIPTION
**Pull request by samwilson**
Add the image as a Leaflet layer as an easy way to get zooming
and panning, and perhaps at some future point to have highlight
of current field.

Bug: https://phabricator.wikimedia.org/T211373

### CODE REVIEW

**Comment by samwilson** [comment]
Yep you should see a frame and zoom controls on every image. :(

Do you have any console errors? Have you cleared local browser cache?

**Comment by samwilson** [comment]
I'm going to get #53 done before this, to reduce the size of this patch.

**Comment by aezell** [comment]
I've cleared the cache. 

I get what looks like a jQuery error when selecting a file from the dropdown when I search. But, continuing to the Translate page still works so I don't think that affects Leaflet.

Once on the Translate page, I don't see any controls. I don't get any console errors.

**Comment by samwilson** [comment]
@aezell we think maybe you were getting an error because of the path to RSVG; that's fixed now (T214742) so maybe this will work.

**Pull request merged**
